# Introduction: The Need for a New Social Covenant {#intro}

On how we got here: Let us tell you a story...

[Insert here: story that gets us to contract vs. covenant - quickly, entertainingly]

## A Republic In Crisis

The Republic is in crisis.

The foundations are ruptured.

Consensus is shattered.

The yearning for "a more perfect union" is abandoned.

Political nihilism conquered.

We must climb the mountain of hope.

Something must be done.

A new social covenant must be forged.

## How Did We Get Here?

[Alternative start: A particular scene]

[Recall the scene of the confirmation hearings for Amy Conen Barrett. Trace out the *mistake* of textual originalism. The mistake follows from treating the Constitution as a "normal" legal contract. From there, introduce the distinction between a contract and a covenant. A *covenant* is what forms a nation and binds it together.]



## The Foundings

### The  Pre-Founding: The Colonial Period ()

### The Founding: A New Nation (1776-1790s)

There was a Declaration of Independence from the Crown. Led to the Constitution, which worked.

The social compact of the Founding broke in the 1850s, triggering the U.S. Civil War.

### The Second Founding: Reconstruction (1865-1870)

The 2nd... was from slavery: the Emancipation Proclamation.  Led to the Second Founding, which worked partially.

This work is the third. This work is motivated as a Declaration of Independence from autocracy.

### Backsliding (1876-1964)

### The Third Founding: The Key Civil Rights Legislation (1964-1965)

[We thus elevate the stakes.] We are in such a condition that this work is essentially a third DoI.

[PL: I never read the Em Proc.] This Declaration must convey the same powerful message that are corresponding in their generality and power of their values to the same level of the first two DoIs.

## The Need for a Fourth Founding, Based on a New Social Covenant

Each of the foundings addresed fundamental questions:

* Who is a member of the society?
* What justifies the creation of government and the exercise of state power?
  - Distinguish: *overt* justification vs. "real" justification.

* What is the form of government?

* What are the foundational values that the society is committed to, and that the government must honor?
* Who has full political rights?

Each of the foundings represents a change in the answers to these questions.

First founding, colonial period:

* Who has rights: White, propertied males.
* Justification:
  - Overt: Divine right of the monarch.
  - "Real": Self-interest
    - Plato, *Republic*: Thracymachus: "might makes right", self-interest is the justification


[Default dynamic:

* Nature abhors a power vacuum
* Thus "might makes right" becomes the ipso facto modus operandi, the default justification

To counter this dynamic, must have firm covenental values that provide an alternative justification for the control and exercise of power, including especially state power and the monopoly over (legitimate) exercise of violence.

Any other justification, w/o the covenental values becomes merely rhetorical dressing for the raw attempt to gain power.

This model is right in front of us right now in the USA 2021. The GQP is exactly this.

**Claim: The abhorrent pursuit of power can *never* create a society that supports human flourishing.**

]

Democracy depends on what we do now. This work is intended as a map of what needs to be done.

We need to make sure that this DoI, and subsequent refounding, works fully.

This is a Declaration about how to organize ourselves with real, inclusive, genuine representative democracy, guided by the values that were already declared from the beginning.


The Foreward presents the rationale for the 5th founding: hard-hitting, blunt, concise, clear, crisp, powerfully motivating the rationale and general structure for the 5th Founding.

Reaction we want: "I see the history; I see the current situation; I see the need; I see the goal."

Elements that will contribute to this kind of a document must be clear, concise, punchy, rhythmically-stated.

Culminating in the 4th Founding.

For each founding:

* What is involved;
* What are the values;

Need parallelism between the first three. Gives credence to the claim we advance that there is a need for the 4th Founding.




What this project is, and why we undertake it.

## Liberal democracy is in big trouble

## A central problem: confusion over our shared basic values





## The project we undertake in this book

Our project in this book is to update social contract theory for the 21st Century and beyond.

We argue that before entering into a social contract, a community must first form its social covenant.

In Part I, we review concepts and examples of social covenants in scripture and in pre-modern history. These covenants typically involved divine sanction or divine command.

In Part II, we review the concept of the *social contract*, and how it grew out of the philosophical environment of the Enlightenment. We also discuss how, where, and why the political project of the Enlightenment went wrong. (Did it?) Spoiler alert: the mistakes were to lose sight of the *sacred and spiritual* nature of the covenant, and to lose sight of *human flourishing* as the *only* appropriate objective for political arrangements.

Starting in Part III, we examine deeply the philosophical foundations of the Enlightenment political project. We focus on the key concepts of *autonomy*, *self-governance*, *reason*, and *eudaemonia* a.k.a. *human flourishing*.

Part IV discusses the political arrangements that underpin conditions that support human flourishing. It investigates how the social covenant relates to the social contract and to the constitution.

In Part V, we propose a new social covenant for the United States. We offer proposed text, and describe the form of ritual ceremony in which it would be adopted, proclaimed, and affirmed.


# (PART) Social Covenants in Scripture and in History {-}

Part I provides an historical survey of social covenants, and an intellectual history of the concepts of social covenants, social contracts, and constitutions.


# As God Commands: Divine Covenants in the Bible

The Hebrew Bible, the Christian Bible, and many other religious and mythological texts offer narratives in which God sets the terms of the social covenant.

## Creation covenants in the Hebrew Bible

### The first creation story

Instrumental skills and abilities.

(What is the Hebrew count-part to “dominion”? What are the nuances in
the Hebrew that “dominion” doesn’t capture? “Stewardship” implies
authority plus responsibility, and limitation on ownership.)


### The second creation story

God blows the spirit into Adam.
The creation covenant: a shared spiritual essence.

Provides to all humanity an equal spiritual basis. (Makes baptism
unnecessary?)

Shared responsibility between humanity and God to maintain and secure
conditions necessary for all living beings to survive and flourish.

Beginning of human moral agency.


## The covenant with Noah

A covenant with all of creation.

Shared responsibility between humanity and God to maintain and secure
conditions necessary for all living beings to survive and flourish.

## The Mosaic covenant

A covenant specifically with the Jewish people.


## Jesus and the Last Supper

"It shall be for you a new and everlasting covenant..."




## Common features of divine covenants

*The covenant creates a **new tribe, community, or nation**.* By participating in the covenant, a collection of individuals forms a new *tribe* - bound together with reciprocal ties of loyalty, responsibility, claims and obligations.

*The **terms** of the covenant define the social compact for the new tribe.

*Entering into the covenant changes the individual participants fundamentally.* The act of joining the tribe is also a event of individual re-birth. It changes who you are.




*God sets the terms.* The asymmetry in power between God and man is absolute.

Because God sets the terms entirely, the covenant cannot really be called a *contract*. A contract is a voluntary agreement between parties that seeks to advance mutual interest. Even if one party entirely sets the terms, others have the option to decline.

In all the biblical covenant stories, there is no sense whatsoever that man has any leverage, any option of refusal. The Covenant is God's gift, and God's command, framed entirely on God's terms. It's not even a take-it-or-leave-it offer: there is no genuine option to leave-it, that one can discern.

(There are other biblical stories that do involve bargaining with the divine, e.g., in the story of Sodom and Gommorah "What if I can find just *ten* righteous men?", or Satan's bargaining with God over the fate of Job. But these are not covenant stories. They don't concern the terms for forming a new community or nation.)

# Athens and Jeruselum: Social covenants in the Greco-Roman World

Athens: the first democracy.

Plato.

Aristotle.



# Medieval and Early Modern Covenants

Continuing the historical survey after the Biblical period.

These covenants invoke divine sanction and mission, but are organized by humans: prophets, kings, community leaders.


## 7th Century: Mohammed and the formation of the muslim *ummah*


## Nordic nations: Egalitarian covenants

### 10th Century: Denmark's "founding" by Haarald Bluetooth

Denmark adopts Christianity, becomes a new nation.

### Iceland


## 17th Century: The Pilgrims at Plymoth Rock

On landing in North America, the pilgrims adopt a new social covenant. They explicitly bind themselves together in a new community, distinct from Europe; and articulate the terms of their association as a Christian brotherhood.


# (PART) The Enlightenment Project {-}


# The Enlightenment Concept of *The Social Contract*

Was the social contract theory that emerged from Locke et al.: Was this
originally meant to be a contract or a covenant? Was it mis-stated?

Rousseau maybe was closer. Concept of "the general will".

Is there such a thing as "a spirit of the people"?
Are "the people" anything more than a collection of individuals engaged in mutually advantageous transactions?
Under what conditions would you sacrifice for the greater good of your people?



# Social covenant, social contract, and the U.S. Constitution


# The breakdown of the Enlightenment project

The French Revolution leads to the Reign of Terror, leads to Napoleon.

Marx. Materialism. The disasterous experiments of state authoritarian socialism. Soviet, Chinese, etc.

This history requires analysis: how did the Enlightenment promise of governance through human reason lead to such humanity-crushing disaster?

What were the key errors?




Contrast:
JFK: "Ask what you can do for your country."
vs Reagan: "Are you better off now than you were four years ago?"

The Republican program since at least 1980 has been a sustained assault on the very idea of community, of the common good.

Claim: A social contract alone cannot bind a nation together. An enduring nation must be bound together by a social covenant.

And in a truly democratic nation, the terms of the social covenant must be developed collaboratively, not imposed from on high.


## Black thought on the U.S. social covenant



# (PART) The Enlightened Self {-}

Part III focuses on the individual human, prior to entering into a social covenant.

# Autonomy, Self-Governance, and Flourishing

In the Enlightenment concept of the self, certain concepts are central:

* *autonomy*, or *self-governance*;
* *reason*;
* Aristotle's concept of *eudaemonia*, translated as *human flourishing*.


Epistemologically, the project adopts an *empirical* approach, based on observation of the senses.

Revealed truths, declarations based on religious scripture, claims grounded on clerical or political authority, received traditions -- these are not held to be sound bases for the discovery of knowledge about the self.

The Enlightenment applies recently-emerged *scientific method* to questions concerning the means and ends of human life.


## Autonomy

*Autonomy* is a central concept in the Enlightenment concept of the self.

**Autonomy != satisfaction of desire**

Rather, a being with autonomy is *self*-governing.

A being that is governed entirely by its desires and appetites is not self-governing.
(Ref: Plato's *Republic*.)


## Reason


## Flourishing

A translation of Aristotle's *eudaemonia*, human flourishing is the proper end of human life. It involves the realization of potential.

*Eudaemodia* is *not* the same as "happiness", and certainly not the same as pleasure, or the satisfaction of desire.

When Jefferson wrote of human's unalienable right to "the pursuit of happiness", *eudaemonia* is what he had in mind.


# Critiques of the Enlightenment Concept of the Self

## Criticisms based on clerical or royal authority


## Criticisms based on scepticism about the efficacy of reason as a guide to human life

The Reign of Terror gave reason a bad name.


# Morality Without God?

## Flourishing, and its relation to the Good

Hume's argument re: "is" and "ought": cannot derive "ought" from "is".

Esp. re: religion: "God commands X; therefore, X ought to be done."

Must add the normative axiom: "God's commands ought to be followed."

G.E. Moore: Introduced the *naturalistic fallacy*.
Target: utilitarianism. Bentham et al.

If you define "good" = "pleasure", then you assert: meaning of *good* = meaning of *pleasure*.

Then it would make no sense to ask:
Q: "Is pleasure good?"

But Q is an informative question.
Therefore, good cannot be defined as pleasure.

Called the *open question argument*.

Involves *paradox of analysis*: If you give an analysis, you  give meaning of things in terms of other terms.

But if analysis is only matching conceptual identity, then analysis cannot generate new information.

Frege: "A = A" is not informative. "A = B" is informative. But

Leads to *sense-reference distinction*.

Fundamental question:
Suppose we want to say that *flourishing is good*.
Can we ask this question?

Could the answer be "No"?
Could we entertain circumstances under which human flourishing is *not* a good thing?

Hypothesis: we cannot say this.
We cannot imagine *any* conditions under which this is false.

Open Question Argument suggests: "pleasure = good" might be false.

**Assertion: Relationship between "flourishing" and "good" is the same as the relationship between "murder" and "immoral" / "morally unjustified".**

**Claim: Instances of the property of "genuine flourishing" will always be a sub-class of the property of "good".**

Key question: Why is it so difficult to imagine instances of flourishing that are not good?

Look for specific instances:

When we see flourishing, why is it so hard to reject the assertion that this is good?


## Divine Command Theory

An intellectual exercise to pull morality back from the Enlightenment ideals -- the authority of reason -- back to a religious foundation.

DCT: Self-interest becomes part of an authoritative hierarchical structure.

Social contract theory based on self-interest inherits the authoritarian structure of self-interests.

### "Huge compromises had to be made"

* The degree to which the financial elite had a huge role in dictating fundamental policies. There was no way to devise the principles that govern the processes that determine policies, without them. They kept, and keep, tilting the balance in their favor.

* Communism tried to uproot the financial people with a new elite.
  - The problem is *control*, not *ownership*.
  - How do you distribute the (rewards of) assets so that the rewards flow fairly?

Unless we find a way to find a fair distribution of the wealth from these assets?


## The Problem of Moral Alienation

If we affirm and follow moral laws solely because of commands (God's or anyone's), then we are not truly moral agents. We are a kind of animal.

This problem is one for all systems that are based on a hierarchical authority, where authority relies essentially on self-interested conception of the self and application of rewards and punishments.

It actually promotes a conception of the self as a self-interested being, a.k.a., *homo economicus*.

Beef w/ salvation-oriented (salvatic?) religions: it's ultimately based on self-interest.

# Economics




# (PART) Designing a Social Covenant on Enlightenment Principles {-}


# Social Contracts, Social Covenants, and Constitutions

## What is a covenant? What is a *social* covenant?

## What is the relationship between a covenant and a contract?

Contracts:

-   are fully dependent on interests
-   are motivated by individual interests of the parties
-   

Covenants:

-   defined by a set of values?

-   not based on mere interest

-   has a notion of the sacred

When you assume individuals have *autonomy*, this precludes the
possibility that any entity (God; Tsar) can have absolute authority.

This why Catholic reconstructionists and Protestant dominionists are making a massive attack on autonomy.


## The role of reason (in the Enlightenment sense) in the discovery of the covenant

Technology will change. Resources, other things will change.


# The Conditions that Support Flourishing

We have been setting up flourishing

... identify the conditions to flourishing, because those conditions then contribute to the good.


## Challenges in Identifying the Conditions that support Flourishing


### Empirical challenges: We can't know


### The design challenge: human flourishing is not uniquely determined

### Evolutionary challenge: Conditions change


# The relationship between the social contract and the social covenant

## Policies are provisional


## The process for revising the social covenant

1.  Human flourishing is the yardstick.
2.  Because of (1), there is some leeway to the modification of the
    elements of the covenant.
3.  The social contract can be modified at higher frequency, with a
    lower threshold. Given changes in conditions…


## The process for amending the social contract



# (PART) Together We Flourish {-}

How to implement these principle in the US for the 21st Century.

# A New Social Covenant for the United States of America

# Implementation in the Constitution, Constitutional Interpretation

# Implementation in Law, legal interpretaton

# Implementation in Education

# Implementation in Media, Communications, the Internet


# Conclusions
