# What is a Social Covenant

What is a *social covenant*? 

A social covenant is the 



## What does a social covenant do?





First, a social covenant establishes (or re-establishes) a community. It says, These people are no longer simply a collection of individuals. They stand in a special relationship to one another. They are now, in a profound sense, one people. 

Invariably, the covenant defines *who is a member of the community*. 

The covenant identifies what it is that binds the community together. Does God command them to join together, and call themselves one people? Are they bound by blood relations? Do they share allegiance to a sovereign power? A religious faith? Is it simply a voluntary association? 

The covenant identifies the

The covenant identifies the *terms* of association, the shared *values*, and some foundational laws that members of the community proclaim, accept, and agree to live by.



## Adopting a social covenant is always ritualized

The adoption of a social covenant *always* takes the form of a ritual. Always. The ritual plays a necessary function in marking -- or perhaps, in creating -- a transformation of the individual. The rituals says: you are no longer exactly the same person as you were before. In joining this community, you are now someone new.

Across geography and time, the rituals of adopting a social covenant share notable commonalities. The entire community assembles. A leadership figure proclaims from a stage. For the most important moments of transformation, the entire congregation stands, signalling the seriousness of the moment. The language used is poetic, not administrative, nor vulgar, not ordinary. Everyone is dressed as well as their resources permit. The mood is solemn.

Periodic rituals reaffirm the commitment to the community.

Always, *symbols* are used to stand for the community as a whole, and indicate membership in it. (Flags, patches, logos, ...).



## The difference between a social covenant, a social contract, and a constitution

Simply put, a constitution is a political document. 

A covenant is poetry. A constitution is prose.


### A social covenant is both political and spiritual




### The terms of the covenant are *incomplete*

The covenant states broad, general principles or values by which the community will live. These values are not stated with legal precision. The statement of principle does not cover all cases of application, and is not intended to.

The covenant does not describe the process of governance. It does not state the number of members in representative political bodies, their powers, and the mechanisms of their selection and replacement. Rather, the covenant states objectives and constraints that governance processes must adhere to.


Why does it matter that the covenant is *incomplete*? 

First, because, practically the covenental statement must be short. It is a broad statement of values, goals, principles. It cannot cover everything. And this is critical: it must not pretend to.

Instead, it offers a way for us as a community to think about how we handle particular challenges. 

What are the rights of the accused? How do we extend freedom of speech and of the press into the age of social media?

We do not look on our constitution as a legal contract between parties drawn together by self-interest. If we did, we might try to excavate what these exact words signified in the late 18th Century. Instead, we look to the values they understood.