# As God Commands: Divine Covenants

The Hebrew Bible, the Christian Bible, and many other religious and mythological texts offer narratives in which God sets the terms of the social covenant.

## Creation covenants in the Hebrew Bible

### The first creation story

Instrumental skills and abilities.

(What is the Hebrew count-part to “dominion”? What are the nuances in
the Hebrew that “dominion” doesn’t capture? “Stewardship” implies
authority plus responsibility, and limitation on ownership.)


### The second creation story

God blows the spirit into Adam. 
The creation covenant: a shared spiritual essence.

Provides to all humanity an equal spiritual basis. (Makes baptism
unnecessary?)

Shared responsibility between humanity and God to maintain and secure
conditions necessary for all living beings to survive and flourish.

Beginning of human moral agency.


## The covenant with Noah

A covenant with all of creation.

Shared responsibility between humanity and God to maintain and secure
conditions necessary for all living beings to survive and flourish.

## The Mosaic covenant

A covenant specifically with the Jewish people.


## Jesus and the Last Supper

"It shall be for you a new and everlasting covenant..."




## Common features of divine covenants

*The covenant creates a **new tribe, community, or nation**.* By participating in the covenant, a collection of individuals forms a new *tribe* - bound together with reciprocal ties of loyalty, responsibility, claims and obligations. 

*The **terms** of the covenant define the social compact for the new tribe.

*Entering into the covenant changes the individual participants fundamentally.* The act of joining the tribe is also a event of individual re-birth. It changes who you are.




*God sets the terms.* The asymmetry in power between God and man is absolute.

Because God sets the terms entirely, the covenant cannot really be called a *contract*. A contract is a voluntary agreement between parties that seeks to advance mutual interest. Even if one party entirely sets the terms, others have the option to decline.

In all the biblical covenant stories, there is no sense whatsoever that man has any leverage, any option of refusal. The Covenant is God's gift, and God's command, framed entirely on God's terms. It's not even a take-it-or-leave-it offer: there is no genuine option to leave-it, that one can discern.

(There are other biblical stories that do involve bargaining with the divine, e.g., in the story of Sodom and Gommorah "What if I can find just *ten* righteous men?", or Satan's bargaining with God over the fate of Job. But these are not covenant stories. They don't concern the terms for forming a new community or nation.)
