# (PART) The Enlightened Self {-} 

Part III focuses on the individual human, prior to entering into a social covenant.

# Autonomy, Self-Governance, and Flourishing

In the Enlightenment concept of the self, certain concepts are central:

* *autonomy*, or *self-governance*;
* *reason*;
* Aristotle's concept of *eudaemonia*, translated as *human flourishing*.


Epistemologically, the project adopts an *empirical* approach, based on observation of the senses. 

Revealed truths, declarations based on religious scripture, claims grounded on clerical or political authority, received traditions -- these are not held to be sound bases for the discovery of knowledge about the self.

The Enlightenment applies recently-emerged *scientific method* to questions concerning the means and ends of human life.


## Autonomy

*Autonomy* is a central concept in the Enlightenment concept of the self.

**Autonomy != satisfaction of desire**

Rather, a being with autonomy is *self*-governing.

A being that is governed entirely by its desires and appetites is not self-governing. 
(Ref: Plato's *Republic*.)


## Reason


## Flourishing

A translation of Aristotle's *eudaemonia*, human flourishing is the proper end of human life. It involves the realization of potential.

*Eudaemodia* is *not* the same as "happiness", and certainly not the same as pleasure, or the satisfaction of desire. 

When Jefferson wrote of human's unalienable right to "the pursuit of happiness", *eudaemonia* is what he had in mind.


# Critiques of the Enlightenment Concept of the Self

## Criticisms based on clerical or royal authority


## Criticisms based on scepticism about the efficacy of reason as a guide to human life

The Reign of Terror gave reason a bad name.


# Morality Without God?

## Flourishing, and its relation to the Good

Hume's argument re: "is" and "ought": cannot derive "ought" from "is".

Esp. re: religion: "God commands X; therefore, X ought to be done."

Must add the normative axiom: "God's commands ought to be followed."

G.E. Moore: Introduced the *naturalistic fallacy*. 
Target: utilitarianism. Bentham et al.

If you define "good" = "pleasure", then you assert: meaning of *good* = meaning of *pleasure*.

Then it would make no sense to ask: 
Q: "Is pleasure good?"

But Q is an informative question.
Therefore, good cannot be defined as pleasure.

Called the *open question argument*.

Involves *paradox of analysis*: If you give an analysis, you  give meaning of things in terms of other terms.

But if analysis is only matching conceptual identity, then analysis cannot generate new information. 

Frege: "A = A" is not informative. "A = B" is informative. But 

Leads to *sense-reference distinction*.

Fundamental question: 
Suppose we want to say that *flourishing is good*. 
Can we ask this question?

Could the answer be "No"?
Could we entertain circumstances under which human flourishing is *not* a good thing?

Hypothesis: we cannot say this. 
We cannot imagine *any* conditions under which this is false.

Open Question Argument suggests: "pleasure = good" might be false.

**Assertion: Relationship between "flourishing" and "good" is the same as the relationship between "murder" and "immoral" / "morally unjustified".**

**Claim: Instances of the property of "genuine flourishing" will always be a sub-class of the property of "good".**

Key question: Why is it so difficult to imagine instances of flourishing that are not good?

Look for specific instances: 

When we see flourishing, why is it so hard to reject the assertion that this is good?


## Divine Command Theory 

An intellectual exercise to pull morality back from the Enlightenment ideals -- the authority of reason -- back to a religious foundation.

DCT: Self-interest becomes part of an authoritative hierarchical structure.

Social contract theory based on self-interest inherits the authoritarian structure of self-interests.

### "Huge compromises had to be made"

* The degree to which the financial elite had a huge role in dictating fundamental policies. There was no way to devise the principles that govern the processes that determine policies, without them. They kept, and keep, tilting the balance in their favor.

* Communism tried to uproot the financial people with a new elite. 
  - The problem is *control*, not *ownership*. 
  - How do you distribute the (rewards of) assets so that the rewards flow fairly? 
  
Unless we find a way to find a fair distribution of the wealth from these assets?


## The Problem of Moral Alienation

If we affirm and follow moral laws solely because of commands (God's or anyone's), then we are not truly moral agents. We are a kind of animal.

This problem is one for all systems that are based on a hierarchical authority, where authority relies essentially on self-interested conception of the self and application of rewards and punishments. 

It actually promotes a conception of the self as a self-interested being, a.k.a., *homo economicus*. 

Beef w/ salvation-oriented (salvatic?) religions: it's ultimately based on self-interest. 

# Economics



