# Autonomy, Self-Governance, and Flourishing

In the Enlightenment concept of the self, certain concepts are central:

* *autonomy*, or *self-governance*;
* *reason*;
* Aristotle's concept of *eudaemonia*, translated as *human flourishing*.


Epistemologically, the project adopts an *empirical* approach, based on observation of the senses. 

Revealed truths, declarations based on religious scripture, claims grounded on clerical or political authority, received traditions -- these are not held to be sound bases for the discovery of knowledge about the self.

The Enlightenment applies recently-emerged *scientific method* to questions concerning the means and ends of human life.


## Autonomy

*Autonomy* is a central concept in the Enlightenment concept of the self.

**Autonomy != satisfaction of desire**

Rather, a being with autonomy is *self*-governing.

A being that is governed entirely by its desires and appetites is not self-governing. 
(Ref: Plato's *Republic*.)


## Reason


## Flourishing

A translation of Aristotle's *eudaemonia*, human flourishing is the proper end of human life. It involves the realization of potential.

*Eudaemodia* is *not* the same as "happiness", and certainly not the same as pleasure, or the satisfaction of desire. 

When Jefferson wrote of human's unalienable right to "the pursuit of happiness", *eudaemonia* is what he had in mind.

