# Critiques of the Enlightenment Concept of the Self

## Criticisms based on clerical or royal authority


## Criticisms based on scepticism about the efficacy of reason as a guide to human life

The Reign of Terror gave reason a bad name.


## Morality Without God?

## Flourishing, and its relation to the Good

Hume's argument re: "is" and "ought": cannot derive "ought" from "is".

Esp. re: religion: "God commands X; therefore, X ought to be done."

Must add the normative axiom: "God's commands ought to be followed."

G.E. Moore: Introduced the *naturalistic fallacy*. 
Target: utilitarianism. Bentham et al.

If you define "good" = "pleasure", then you assert: meaning of *good* = meaning of *pleasure*.

Then it would make no sense to ask: 
Q: "Is pleasure good?"

But Q is an informative question.
Therefore, good cannot be defined as pleasure.

Called the *open question argument*.

Involves *paradox of analysis*: If you give an analysis, you  give meaning of things in terms of other terms.

But if analysis is only matching conceptual identity, then analysis cannot generate new information. 

Frege: "A = A" is not informative. "A = B" is informative. But 

Leads to *sense-reference distinction*.

Fundamental question: 
Suppose we want to say that *flourishing is good*. 
Can we ask this question?

Could the answer be "No"?
Could we entertain circumstances under which human flourishing is *not* a good thing?

Hypothesis: we cannot say this. 
We cannot imagine *any* conditions under which this is false.

Open Question Argument suggests: "pleasure = good" might be false.

**Assertion: Relationship between "flourishing" and "good" is the same as the relationship between "murder" and "immoral" / "morally unjustified".**

**Claim: Instances of the property of "genuine flourishing" will always be a sub-class of the property of "good".**

Key question: Why is it so difficult to imagine instances of flourishing that are not good?

Look for specific instances: 

When we see flourishing, why is it so hard to reject the assertion that this is good?

