# Divine Command Theory 

An intellectual exercise to pull morality back from the Enlightenment ideals -- the authority of reason -- back to a religious foundation.

DCT: Self-interest becomes part of an authoritative hierarchical structure.

Social contract theory based on self-interest inherits the authoritarian structure of self-interests.

### "Huge compromises had to be made"

* The degree to which the financial elite had a huge role in dictating fundamental policies. There was no way to devise the principles that govern the processes that determine policies, without them. They kept, and keep, tilting the balance in their favor.

* Communism tried to uproot the financial people with a new elite. 
  - The problem is *control*, not *ownership*. 
  - How do you distribute the (rewards of) assets so that the rewards flow fairly? 
  
Unless we find a way to find a fair distribution of the wealth from these assets?


## The Problem of Moral Alienation

If we affirm and follow moral laws solely because of commands (God's or anyone's), then we are not truly moral agents. We are a kind of animal.

This problem is one for all systems that are based on a hierarchical authority, where authority relies essentially on self-interested conception of the self and application of rewards and punishments. 

It actually promotes a conception of the self as a self-interested being, a.k.a., *homo economicus*. 

Beef w/ salvation-oriented (salvatic?) religions: it's ultimately based on self-interest. 
