# (PART) Designing a Social Covenant on Enlightenment Principles {-} 


# Social Contracts, Social Covenants, and Constitutions

## What is a covenant? What is a *social* covenant?

## What is the relationship between a covenant and a contract?

Contracts:

-   are fully dependent on interests
-   are motivated by individual interests of the parties
-   

Covenants:

-   defined by a set of values?

-   not based on mere interest

-   has a notion of the sacred

When you assume individuals have *autonomy*, this precludes the
possibility that any entity (God; Tsar) can have absolute authority.

This why Catholic reconstructionists and Protestant dominionists are making a massive attack on autonomy.


## The role of reason (in the Enlightenment sense) in the discovery of the covenant

Technology will change. Resources, other things will change.


# The Conditions that Support Flourishing

We have been setting up flourishing

... identify the conditions to flourishing, because those conditions then contribute to the good.


## Challenges in Identifying the Conditions that support Flourishing


### Empirical challenges: We can't know


### The design challenge: human flourishing is not uniquely determined

### Evolutionary challenge: Conditions change


# The relationship between the social contract and the social covenant

## Policies are provisional


## The process for revising the social covenant

1.  Human flourishing is the yardstick.
2.  Because of (1), there is some leeway to the modification of the
    elements of the covenant.
3.  The social contract can be modified at higher frequency, with a
    lower threshold. Given changes in conditions…


## The process for amending the social contract
